import { google } from 'googleapis';
import { getCredentials } from '../connections.js';
import { createOAuthState, getMailAccount, registerMailAccount, updateMailAccount } from '../../mail/store.js';

export const id = 'gmail';
const SCOPES = ['https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.labels'];
const clean = (value, length = 2000) => String(value ?? '').trim().slice(0, length);

function oauth(credentials = getCredentials('gmail')) {
  if (!clean(credentials.clientId) || !clean(credentials.clientSecret)) throw new Error('Save Google OAuth client ID and secret in Connections before authorizing Gmail.');
  return new google.auth.OAuth2(credentials.clientId, credentials.clientSecret, credentials.redirectUri || process.env.GMAIL_REDIRECT_URI || 'http://localhost:4455/api/mail/oauth/callback');
}
function mimeBase64(headers, text) { return Buffer.from(`${Object.entries(headers).map(([key, value]) => `${key}: ${value}`).join('\r\n')}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${text}`, 'utf8').toString('base64url'); }
function header(message, name) { return (message.payload?.headers || []).find((item) => item.name.toLowerCase() === name.toLowerCase())?.value || ''; }
function decodeBody(part) { const data = part?.body?.data || ''; return data ? Buffer.from(data, 'base64url').toString('utf8') : ''; }
function messageText(payload) { if (!payload) return ''; if (payload.mimeType === 'text/plain') return decodeBody(payload); return (payload.parts || []).map(messageText).find(Boolean) || decodeBody(payload); }
function youtubeEvent(message) { const from = header(message, 'From').toLowerCase(); const subject = header(message, 'Subject'); const body = messageText(message.payload); const all = `${subject}\n${body}`; const remoteVideoId = all.match(/(?:youtu\.be\/|[?&]v=)([A-Za-z0-9_-]{6,})/)?.[1] || ''; const sourceIsYoutube = /youtube\.com/.test(from); const lower = all.toLowerCase(); let category='other'; let severity='info'; if (sourceIsYoutube && /copyright|claim/.test(lower)) { category='copyright'; severity='warn'; } else if (sourceIsYoutube && /strike|community guidelines/.test(lower)) { category='strike'; severity='critical'; } else if (sourceIsYoutube && /comment/.test(lower)) category='comment'; else if (sourceIsYoutube && /processed|rejected|upload/.test(lower)) { category='processing'; severity=/rejected|failed/.test(lower)?'warn':'info'; } else if (sourceIsYoutube && /monetization/.test(lower)) category='monetization'; return { parserId: sourceIsYoutube ? `youtube.${category}` : 'generic.unmatched', category, severity, remoteVideoId, title: subject, detail: clean(body, 2000), body };
}

export async function testConnection(credentials = {}) { try { oauth(credentials); return { ok: true, detail: 'OAuth client configuration is ready. Authorize a mailbox to enable tracking.' }; } catch (error) { return { ok: false, error: error.message }; } }
export function startAuthorization() { const client = oauth(); const state = createOAuthState(); return client.generateAuthUrl({ access_type: 'offline', prompt: 'consent', scope: SCOPES, state }); }
export async function completeAuthorization({ code, state }) { const client = oauth(); const { consumeOAuthState } = await import('../../mail/store.js'); consumeOAuthState(state); const { tokens } = await client.getToken(clean(code, 4000)); if (!tokens.refresh_token) throw new Error('Google did not return a refresh token. Revoke the app access and authorize again with consent.'); client.setCredentials(tokens); const profile = await google.oauth2({ version: 'v2', auth: client }).userinfo.get(); return registerMailAccount({ emailAddress: profile.data.email, displayName: profile.data.name || '', refreshToken: tokens.refresh_token, scopes: SCOPES, labelPrefix: getCredentials('gmail').labelPrefix || 'Studio' }); }
async function gmailForAccount(accountId) { const account = getMailAccount(accountId, { includeCredential: true }); const client = oauth(); client.setCredentials({ refresh_token: account.refreshToken }); return { account, gmail: google.gmail({ version: 'v1', auth: client }) }; }
export async function ensureLabels(accountId, paths = []) { const { account, gmail } = await gmailForAccount(accountId); const existing = await gmail.users.labels.list({ userId: 'me' }); const labels = { ...account.labels }; for (const path of paths.map((item) => clean(item, 225)).filter(Boolean)) { let row = (existing.data.labels || []).find((label) => label.name === path); if (!row) row = (await gmail.users.labels.create({ userId: 'me', requestBody: { name: path, labelListVisibility: 'labelShow', messageListVisibility: 'show' } })).data; labels[path] = row.id; } updateMailAccount(accountId, { labels }); return labels; }
export async function send(accountId, message = {}) { const { account, gmail } = await gmailForAccount(accountId); const labelPath = clean(message.labelPath || `${account.labelPrefix}/Tracking`, 225); const labels = await ensureLabels(accountId, [labelPath]); const subject = clean(message.subject || 'Studio video update', 900); const headers = { To: account.emailAddress, From: account.emailAddress, Subject: subject, 'Message-ID': message.rfc822Id || `<studio-${Date.now()}@local>` }; if (message.inReplyTo) { headers['In-Reply-To'] = message.inReplyTo; headers.References = message.inReplyTo; } const response = await gmail.users.messages.send({ userId: 'me', requestBody: { raw: mimeBase64(headers, clean(message.text, 20000)), ...(message.gmailThreadId ? { threadId: message.gmailThreadId } : {}) } }); if (labels[labelPath]) await gmail.users.messages.modify({ userId: 'me', id: response.data.id, requestBody: { addLabelIds: [labels[labelPath]] } }); return { gmailMessageId: response.data.id || '', gmailThreadId: response.data.threadId || '', rfc822Id: headers['Message-ID'], labelPath, subject }; }
export async function sync(accountId) { const { gmail } = await gmailForAccount(accountId); const list = await gmail.users.messages.list({ userId: 'me', q: 'newer_than:30d', maxResults: 100 }); const messages=[]; for (const item of list.data.messages || []) { const full = await gmail.users.messages.get({ userId: 'me', id: item.id, format: 'full' }); messages.push({ id: full.data.id, threadId: full.data.threadId, from: header(full.data, 'From'), subject: header(full.data, 'Subject'), receivedAt: new Date(Number(full.data.internalDate || Date.now())).toISOString(), labels: full.data.labelIds || [], ...youtubeEvent(full.data) }); } updateMailAccount(accountId, { historyId: list.data.historyId || '', lastSyncAt: new Date().toISOString(), lastError: '', status: 'ok' }); return { messages, historyId: list.data.historyId || '' }; }
