import { randomUUID } from 'crypto';
import db from '../db/sqlite.js';
import { decryptSecret, encryptSecret } from '../security/secrets.js';

const now = () => new Date().toISOString();
const json = (value, fallback = {}) => { try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
const text = (value, length = 2000) => String(value ?? '').trim().slice(0, length);

function publicAccount(row) {
  if (!row) return null;
  return { id: row.id, provider: row.provider, emailAddress: row.email_address, displayName: row.display_name, youtubeChannelId: row.youtube_channel_id, labelPrefix: row.label_prefix, scopes: json(row.scopes_json, []), historyId: row.history_id, lastSyncAt: row.last_sync_at, lastError: row.last_error, status: row.status, enabled: Boolean(row.enabled), createdAt: row.created_at, updatedAt: row.updated_at };
}

export function listMailAccounts() { return db.prepare('SELECT * FROM mail_accounts ORDER BY email_address').all().map(publicAccount); }
export function getMailAccount(id, { includeCredential = false } = {}) {
  const row = db.prepare('SELECT * FROM mail_accounts WHERE id = ?').get(text(id, 128));
  if (!row) throw new Error(`Mail account not found: ${id}`);
  const account = publicAccount(row);
  return includeCredential ? { ...account, refreshToken: decryptSecret(row.credential_ref), labels: json(row.labels_json, {}) } : account;
}
export function registerMailAccount(input = {}) {
  const emailAddress = text(input.emailAddress, 320).toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailAddress)) throw new Error('A valid Gmail address is required');
  const existing = db.prepare('SELECT id FROM mail_accounts WHERE email_address = ?').get(emailAddress);
  const id = existing?.id || randomUUID(); const stamp = now();
  db.prepare(`INSERT INTO mail_accounts (id, provider, email_address, display_name, youtube_channel_id, label_prefix, credential_ref, scopes_json, labels_json, history_id, last_sync_at, last_error, status, enabled, created_at, updated_at)
    VALUES (?, 'gmail', ?, ?, ?, ?, ?, ?, '{}', '', '', '', 'configured', 0, ?, ?)
    ON CONFLICT(email_address) DO UPDATE SET display_name=excluded.display_name, youtube_channel_id=excluded.youtube_channel_id, label_prefix=excluded.label_prefix, credential_ref=excluded.credential_ref, scopes_json=excluded.scopes_json, status='configured', last_error='', updated_at=excluded.updated_at`
  ).run(id, emailAddress, text(input.displayName, 240), text(input.youtubeChannelId, 128), text(input.labelPrefix || 'Studio', 100) || 'Studio', encryptSecret(input.refreshToken), JSON.stringify(Array.isArray(input.scopes) ? input.scopes : []), stamp, stamp);
  return getMailAccount(id);
}
export function setMailAccountEnabled(id, enabled) { const account = getMailAccount(id); if (enabled && account.status !== 'ok' && account.status !== 'configured') throw new Error('Test the Gmail account before enabling it'); db.prepare('UPDATE mail_accounts SET enabled=?, updated_at=? WHERE id=?').run(enabled ? 1 : 0, now(), account.id); return getMailAccount(account.id); }
export function updateMailAccount(id, patch = {}) { const account = getMailAccount(id); db.prepare('UPDATE mail_accounts SET history_id=?, last_sync_at=?, last_error=?, status=?, labels_json=?, updated_at=? WHERE id=?').run(patch.historyId ?? account.historyId, patch.lastSyncAt ?? account.lastSyncAt, patch.lastError ?? account.lastError, patch.status ?? account.status, patch.labels === undefined ? JSON.stringify(getMailAccount(id, { includeCredential: true }).labels) : JSON.stringify(patch.labels), now(), account.id); return getMailAccount(account.id); }

export function createOAuthState() { const state = randomUUID(); const createdAt = now(); const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString(); db.prepare('DELETE FROM mail_oauth_states WHERE expires_at < ?').run(createdAt); db.prepare('INSERT INTO mail_oauth_states (state, created_at, expires_at) VALUES (?, ?, ?)').run(state, createdAt, expiresAt); return state; }
export function consumeOAuthState(state) { const row = db.prepare('SELECT state FROM mail_oauth_states WHERE state=? AND expires_at >= ?').get(text(state, 200), now()); db.prepare('DELETE FROM mail_oauth_states WHERE state=?').run(text(state, 200)); if (!row) throw new Error('The Gmail authorization link expired or was already used. Start again.'); }

export function listEnabledMailAccounts() { return db.prepare("SELECT * FROM mail_accounts WHERE enabled=1 AND status IN ('configured','ok') ORDER BY email_address").all().map(publicAccount); }
export function enqueueMail(accountId, { videoId = '', jobId = null, eventKind, dedupeKey, payload = {} }) { const stamp = now(); return db.prepare(`INSERT OR IGNORE INTO mail_outbox (account_id, video_id, job_id, event_kind, dedupe_key, payload_json, status, attempts, max_attempts, next_retry_at, last_error, claimed_at, worker_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, 'queued', 0, 5, '', '', '', '', ?, ?)`).run(accountId, text(videoId, 128), jobId || null, text(eventKind, 100), text(dedupeKey, 500), JSON.stringify(payload || {}), stamp, stamp).changes; }
export function claimMailOutbox(workerId) { return db.transaction(() => { const row = db.prepare("SELECT * FROM mail_outbox WHERE status='queued' AND (next_retry_at='' OR next_retry_at<=?) ORDER BY created_at LIMIT 1").get(now()); if (!row) return null; const stamp = now(); const changed = db.prepare("UPDATE mail_outbox SET status='sending', attempts=attempts+1, claimed_at=?, worker_id=?, updated_at=? WHERE id=? AND status='queued'").run(stamp, text(workerId, 200), stamp, row.id).changes; return changed ? db.prepare('SELECT * FROM mail_outbox WHERE id=?').get(row.id) : null; })(); }
export function markMailOutbox(id, { error = '', retry = false } = {}) { const stamp = now(); if (!error) return db.prepare("UPDATE mail_outbox SET status='sent', last_error='', updated_at=? WHERE id=?").run(stamp, id); const row = db.prepare('SELECT attempts,max_attempts FROM mail_outbox WHERE id=?').get(id); const retries = retry && row && row.attempts < row.max_attempts; const nextRetry = retries ? new Date(Date.now() + Math.min(60 * 60_000, 1000 * (2 ** row.attempts))).toISOString() : ''; return db.prepare('UPDATE mail_outbox SET status=?, last_error=?, next_retry_at=?, updated_at=? WHERE id=?').run(retries ? 'queued' : 'failed', text(error, 2000), nextRetry, stamp, id); }
export function recoverStaleMailOutbox(maxAgeMs = 15 * 60_000) { const before = new Date(Date.now() - maxAgeMs).toISOString(); return db.prepare("UPDATE mail_outbox SET status='queued', claimed_at='', worker_id='', updated_at=? WHERE status='sending' AND claimed_at < ?").run(now(), before).changes; }
export function recordMailMessage(input = {}) { const stamp = now(); const result = db.prepare(`INSERT OR IGNORE INTO mail_messages (account_id, thread_row_id, video_id, direction, gmail_message_id, gmail_thread_id, rfc822_id, from_addr, subject, snippet, body_text, labels_json, event_kind, sent_at, received_at, raw_headers_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(text(input.accountId, 128), input.threadRowId || null, text(input.videoId, 128), text(input.direction, 30), text(input.gmailMessageId, 300), text(input.gmailThreadId, 300), text(input.rfc822Id, 300), text(input.fromAddress, 320), text(input.subject, 1000), text(input.snippet, 2000), text(input.bodyText, 100000), JSON.stringify(input.labels || []), text(input.eventKind, 100), text(input.sentAt, 80), text(input.receivedAt, 80), JSON.stringify(input.rawHeaders || {}), stamp); return Number(result.lastInsertRowid || 0); }
export function upsertMailThread({ videoId, accountId, gmailThreadId = '', rfc822RootId = '', subject = '', labelPath = '', status = '' }) { const stamp = now(); db.prepare(`INSERT INTO video_mail_threads (video_id,account_id,gmail_thread_id,rfc822_root_id,subject,label_path,message_count,last_status,created_at,updated_at) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?, ?) ON CONFLICT(video_id,account_id) DO UPDATE SET gmail_thread_id=CASE WHEN excluded.gmail_thread_id!='' THEN excluded.gmail_thread_id ELSE video_mail_threads.gmail_thread_id END, message_count=video_mail_threads.message_count+1,last_status=excluded.last_status,updated_at=excluded.updated_at`).run(videoId, accountId, gmailThreadId, rfc822RootId, subject, labelPath, status, stamp, stamp); return db.prepare('SELECT * FROM video_mail_threads WHERE video_id=? AND account_id=?').get(videoId, accountId); }
export function listVideoMailTimeline(videoId) { return db.prepare(`SELECT m.*, i.category, i.severity, i.title AS ingest_title, i.detail, i.acknowledged_at FROM mail_messages m LEFT JOIN mail_ingest_events i ON i.message_row_id=m.id WHERE m.video_id=? ORDER BY COALESCE(m.received_at,m.sent_at,m.created_at) ASC`).all(text(videoId, 128)).map((row) => ({ id: row.id, direction: row.direction, eventKind: row.event_kind, subject: row.subject, snippet: row.snippet, sentAt: row.sent_at, receivedAt: row.received_at, category: row.category || '', severity: row.severity || '', detail: row.detail || '', acknowledgedAt: row.acknowledged_at || '' })); }
export function listMailInbox({ severity = '', unacknowledged = false, unmatched = false, limit = 100 } = {}) { const clauses=[]; const values=[]; if (severity) { clauses.push('i.severity=?'); values.push(text(severity,40)); } if (unacknowledged) clauses.push("i.acknowledged_at='' "); if (unmatched) clauses.push("i.video_id='' "); values.push(Math.max(1, Math.min(200, Number(limit)||100))); return db.prepare(`SELECT i.*,m.subject,m.snippet,vr.title AS video_title FROM mail_ingest_events i JOIN mail_messages m ON m.id=i.message_row_id LEFT JOIN video_records vr ON vr.id=i.video_id ${clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''} ORDER BY i.occurred_at DESC LIMIT ?`).all(...values).map((row) => ({ id:row.id, category:row.category,severity:row.severity,title:row.title,detail:row.detail,videoId:row.video_id,videoTitle:row.video_title||'',subject:row.subject,snippet:row.snippet,receivedAt:row.occurred_at,acknowledgedAt:row.acknowledged_at })); }
export function acknowledgeMailEvent(id) { db.prepare('UPDATE mail_ingest_events SET acknowledged_at=? WHERE id=?').run(now(), Number(id)); }
